//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ProjectArticleXREFs = new HashSet<ProjectArticleXREF>();
            this.Outreaches = new HashSet<Outreach>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public int ArticleStatusId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ArticleStatus ArticleStatus { get; set; }
        public virtual ICollection<ProjectArticleXREF> ProjectArticleXREFs { get; set; }
        public virtual ICollection<Outreach> Outreaches { get; set; }
    }
}
