//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeTeamXREFs = new HashSet<EmployeeTeamXREF>();
            this.OrderEmployeeXREFs = new HashSet<OrderEmployeeXREF>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<EmployeeTeamXREF> EmployeeTeamXREFs { get; set; }
        public virtual ICollection<OrderEmployeeXREF> OrderEmployeeXREFs { get; set; }
    }
}
