//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingPageKeywordXREF
    {
        public int Id { get; set; }
        public int LandingPageId { get; set; }
        public int KeywordId { get; set; }
        public int KeywordPriority { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual LandingPage LandingPage { get; set; }
    }
}
