//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public Link()
        {
            this.Outreaches = new HashSet<Outreach>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string TargetUrl { get; set; }
        public string RootUrl { get; set; }
        public string RootMethod { get; set; }
        public int LinkStrategyId { get; set; }
        public string AnchorText { get; set; }
        public int DomainAuthority { get; set; }
        public int PageRelevance { get; set; }
        public int SiteRelevance { get; set; }
        public int LinkLocationId { get; set; }
        public string PublishedUrl { get; set; }
        public string LandingPage { get; set; }
        public int LinkStatusId { get; set; }
        public Nullable<System.DateTime> DateFound { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public string FoundBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string AcquiredBy { get; set; }
        public int LinkBuildingModeId { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string ContactUrl { get; set; }
        public string Notes { get; set; }
        public int LinkTypeId { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<int> ProjectArticleXREFId { get; set; }
        public bool IsWinner { get; set; }
    
        public virtual LinkBuildingMode LinkBuildingMode { get; set; }
        public virtual LinkLocation LinkLocation { get; set; }
        public virtual LinkStatus LinkStatus { get; set; }
        public virtual LinkStrategy LinkStrategy { get; set; }
        public virtual LinkType LinkType { get; set; }
        public virtual ProjectArticleXREF ProjectArticleXREF { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<Outreach> Outreaches { get; set; }
    }
}
