//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Outreaches = new HashSet<Outreach>();
            this.PersonaSocialAccountXREFs = new HashSet<PersonaSocialAccountXREF>();
            this.ProjectPersonaXREFs = new HashSet<ProjectPersonaXREF>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Experience { get; set; }
        public string ConnectionToCustomer { get; set; }
        public string Bio { get; set; }
        public string Notes { get; set; }
        public string GmailUsername { get; set; }
        public string GmailPassword { get; set; }
        public string DomainUsername { get; set; }
        public string DomainPassword { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Email { get; set; }
        public string SMTPServer { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public string SMTPUsername { get; set; }
        public string SMTPPassword { get; set; }
    
        public virtual ICollection<Outreach> Outreaches { get; set; }
        public virtual ICollection<PersonaSocialAccountXREF> PersonaSocialAccountXREFs { get; set; }
        public virtual ICollection<ProjectPersonaXREF> ProjectPersonaXREFs { get; set; }
    }
}
