//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Links = new HashSet<Link>();
            this.OrderEmployeeXREFs = new HashSet<OrderEmployeeXREF>();
            this.OrderTeamXREFs = new HashSet<OrderTeamXREF>();
            this.ProjectArticleXREFs = new HashSet<ProjectArticleXREF>();
            this.ProjectKeywordXREFs = new HashSet<ProjectKeywordXREF>();
            this.ProjectLandingPageXREFs = new HashSet<ProjectLandingPageXREF>();
            this.ProjectPersonaXREFs = new HashSet<ProjectPersonaXREF>();
            this.TimeEntries = new HashSet<TimeEntry>();
            this.ProjectSocialAccountXREFs = new HashSet<ProjectSocialAccountXREF>();
            this.OrderCategoryXREFs = new HashSet<OrderCategoryXREF>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CustomerId { get; set; }
        public bool IsActive { get; set; }
        public string Categories { get; set; }
        public int BillingCycleId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Strategy { get; set; }
        public string SpecialRequirements { get; set; }
        public string BigWin { get; set; }
    
        public virtual BillingCycle BillingCycle { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual ICollection<OrderEmployeeXREF> OrderEmployeeXREFs { get; set; }
        public virtual ICollection<OrderTeamXREF> OrderTeamXREFs { get; set; }
        public virtual ICollection<ProjectArticleXREF> ProjectArticleXREFs { get; set; }
        public virtual ICollection<ProjectKeywordXREF> ProjectKeywordXREFs { get; set; }
        public virtual ICollection<ProjectLandingPageXREF> ProjectLandingPageXREFs { get; set; }
        public virtual ICollection<ProjectPersonaXREF> ProjectPersonaXREFs { get; set; }
        public virtual ICollection<TimeEntry> TimeEntries { get; set; }
        public virtual ICollection<ProjectSocialAccountXREF> ProjectSocialAccountXREFs { get; set; }
        public virtual ICollection<OrderCategoryXREF> OrderCategoryXREFs { get; set; }
    }
}
