//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialAccount
    {
        public SocialAccount()
        {
            this.PersonaSocialAccountXREFs = new HashSet<PersonaSocialAccountXREF>();
            this.ProjectSocialAccountXREFs = new HashSet<ProjectSocialAccountXREF>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual ICollection<PersonaSocialAccountXREF> PersonaSocialAccountXREFs { get; set; }
        public virtual ICollection<ProjectSocialAccountXREF> ProjectSocialAccountXREFs { get; set; }
    }
}
