//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    
    public partial class sp_Articles_DYNAMIC_SEARCH_Result3
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public int ArticleStatusId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Id1 { get; set; }
        public string Name { get; set; }
        public int Id2 { get; set; }
        public int ProjectId { get; set; }
        public int ArticleId { get; set; }
        public int Id3 { get; set; }
        public string Name1 { get; set; }
        public string Description { get; set; }
        public int CustomerId { get; set; }
        public bool IsActive { get; set; }
        public string Categories { get; set; }
        public int BillingCycleId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Strategy { get; set; }
        public string SpecialRequirements { get; set; }
        public string BigWin { get; set; }
        public Nullable<int> Id4 { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<System.DateTime> InsertDate1 { get; set; }
    }
}
