//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1p.Data
{
    using System;
    
    public partial class sp_Hours_Aggregates_By_Project_Result1
    {
        public string Name { get; set; }
        public Nullable<decimal> ProjectAggregate { get; set; }
    }
}
